version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres_wotracker
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgres
    env_file:
      - env-stack.local