name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          make install

      - name: Run build
        run: make build

      - name: Run vet & lint
        run: make check-ci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic test/**/*.go
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2